### ISSUE TITLE
Document how to use vimperator@mozdev.org filepath for development

### ISSUE THREAD

**Issue by gkatsev** [vimperator/vimperator-labs#168]
# general steps
1. find the [location of your firefox profile](http://kb.mozillazine.org/Profile_folder_-_Firefox)
2. go into the `extensions` folder
3. delete `vimeprator@mozdev.org.xpi` file
4. create a `vimperator@mozdev.org` file
5. in that file, put in the absolute path to the vimperator folder (the one with the `install.rdf` in it)
   - i.e., `/home/gkatsev/p/vimperator-labs/vimperator`
6. restart firefox
- [ ] find MDN documentation about this to link to as well.

**Comment by maxauthority** [comment]
Wouldn't that be a great entry for starting our wiki? :) Although this is even listed on our offical homepage at http://www.vimperator.org/developerinfo

**Comment by gkatsev** [comment]
github projects tend to have a `CONTRIBUTING.md` file for this type of info. We should pull in the info from the website into it as well.

**Comment by maxauthority** [comment]
Ah ok, also good to know. Then having that as well may be a good thing.

**Comment by gkatsev** [comment]
Also, when creating a new issue, github will put a link to a `CONTRIBUTING.md` file if exists.

**Comment by gkatsev** [comment]
Also, I totally forgot about the website :P

**Comment by timss** [comment]
I could help out with this if there's still any interest. Maybe even add an issue and/or pull request template. I'm thinking it should contain at minimum the vimperator version, firefox version and any relevant configuration. 

https://help.github.com/articles/helping-people-contribute-to-your-project/

I'll create a pull request later, and we can take it from there.

**Comment by gkatsev** [comment]
A CONTRIBUTING.md would be great.

**Comment by timss** [comment]
Hm, looked a bit into this and maybe it makes the most sense to rename `HACKING` to `.github/CONTRIBUTING.md`? It already contains much of what would be in a `CONTRIBUTING.md`

It might need an update as far as coding style goes though, but that is outside my domain.

**Comment by maxauthority** [comment]
Sounds good to me. Does the CONTRIBUTING.md show up automatically in certain places of GitHub or is it really jsut a convention?

**Comment by timss** [comment]
Automatically when creating a new issue. Maybe more that I don't know of.

**Comment by gkatsev** [comment]
Renaming `HACKING` to `CONTRIBUTING.md makes sense to me. Though, personally, I think it should be in the root directly and not in the `.github` directory.

**Comment by timss** [comment]
All right. 

What about #450, should it be moved tot the root directory as well?

**Comment by timss** [comment]
Appearantly Github will present `CONTRIBUTING.asciidoc` as well. Maybe we should stick with AsciiDoc instead of Markdown since the rest is already AsciiDoc?

Example:
- https://github.com/elastic/elasticsearch-perl/issues/new
- https://github.com/elastic/elasticsearch-perl/blob/master/CONTRIBUTING.asciidoc

In that case, I'll rename `HACKING` to `CONTRIBUTING.asciidoc` and incorporate the changes done in #451

**Comment by gkatsev** [comment]
I think we should move to markdown, it's a lot simpler and more well known nowadays.

**Comment by gkatsev** [comment]
Yeah, the issue template should also probably just move to the root.

**Comment by maxauthority** [comment]
I agree with both:
1) I don't care so much about markdown or asciidoc, but I fully agree to
just have one text format for all files which we have. And yeah, it seems
Markdown has a huge trend currently and seems simpler.
2) Put the things in the root directory. They also make sense even when we
don't use github anymore and are much more accessible there instead of in a
hidden directory.

**Comment by timss** [comment]
All righty. I'll look into it.

**Comment by timss** [comment]
Please review #450 again.

**Comment by timss** [comment]
`CONTRIBUTING.md` is now fixed, but `{vimperator/muttator}/NEWS` is still in AsciiDoc format. 

1. Should we leave this as it is and include a `.gitattributes` which renders it correctly on Github as AsciiDoc?

        vimperator/NEWS linguist-language=AsciiDoc
        muttator/NEWS linguist-language=AsciiDoc

2. Or format it to Markdown?

While I like Markdown, in this case I'm almost leaning towards 1. because it won't mess up the history in the NEWS files, which can be particularly useful with Git blame (cli or on Github).

Thoughts? Minor issue, but I'd like to wrap up this stuff :-)
(`README.md` hopefully on its way).

**Comment by timss** [comment]
I tried compiling the news entries as asciidoc and the result looks malformed. Maybe I'm doing something wrong, or they're not in proper asciidoc format. Seems that it might be better to just leave it alone, than mess up the history as mentioned in previous comment.

Anyway, this issue is solved as of #451. Should we close this issue?
