### ISSUE TITLE
Tiles on DuckDuckGo (and similar issues on other sites)

### ISSUE THREAD

**Issue by skoogit** [vimperator/vimperator-labs#172]
The "Tiles" (i.e. Images, Videos, Meanings e.t.c.) on DuckDuckGo is not hintable by Vimperator.

Currently I've just written a small site specific userscript to place a dummy onclick attribute on them to get it working, but seeing as there are other sites with "hidden javascript" behind elements that Vimperator doesn't recognize I believe this a issue worthy of evalution, if it's possible to create a general fix.

**Comment by timss** [comment]
Are you using the latest version? Seems to work fine here.

https://github.com/vimperator/vimperator-labs/releases

**Comment by skoogit** [comment]
I was using the version from addons.mozilla.org, however, the latest release didn't fix the problem either.

Here's how it looks:
[No userscript](https://img.bi/#/lOGBCHl!tynNsRSPa2oYOqPqspY6TDf3pbwpIwEPX5Uy0Edl)
[With userscript](https://img.bi/#/Odw9Njs!sMT275DJ5iupTuuGqOhhDtf3HA8qEsv5cWcD4FCm)

**Comment by timss** [comment]
Ah, I thought you meant the "[tabs](http://i.imgur.com/yTugrYx.png)". I'm seeing the same behavior.

Please do share your userscript.

**Comment by skoogit** [comment]
https://greasyfork.org/en/scripts/7919-vimperator-duckduckgo-tile-hints

**Comment by timss** [comment]
Thanks!

**Comment by gkatsev** [comment]
You can update vimperator's hinttags (`:h 'hinttags'`) to support the DDG's tiles. Unfortuantely, it's done via xpath. For example, DDG's tiles have the class of `tile` attached. I used a css-selector to xpath converter to get the xpath for it: [`descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' tile ')]`](http://css2xpath.appspot.com/?format=html&css=.tile).
vimperator will now know to make those into hints.
But this reminds me that it would be cool to put in css selectors instead of xpath for things like hinttags because xpath is dead.
