### ISSUE TITLE
Is it possible to record a macro in .vimperatorrc?

### ISSUE THREAD

**Issue by Andre0991** [vimperator/vimperator-labs#178]
First, thanks for this amazing plugin.

I know that macros are saved in the macros file in the .vimperator folder, but I feel that saving my favourite ones in .vimperatorrc would be a more portable solution.

I tried to put the following line:
```
let @d = '<M-c>tcambridge.dictionary.org/dictionary/british/<M-v><CR>'
```
but it didn't work.

**Comment by Andre0991** [comment]
It seems that is impossible to remove an issue, so here we go:

I can just use noremap. Not sure whether this makes any difference semantically, but it works for my purposes.

**Comment by maxauthority** [comment]
I am not sure if we can save macros in the .vimperatorrc but if you add
one, it should at least persist across restarts (which doesn't help you if
you want to sync settings across multiple computers).


There is, however a slight difference between macros, namely that macros
make some attempts to let web pages load before continuing to push keys. So
opening a tab, waiting for it to load and then something like "gi" to focus
the first textfield is not possible with mappings, but should with macros
(although that "loaded" detection is also not working perfectly since web
pages are so dynamic with lots of javascript).

**Comment by Andre0991** [comment]
Thanks for pointing that out. Good to know.
