### ISSUE TITLE
quick hints should use alphanumerics instead of just numbers

### ISSUE THREAD

**Issue by k0ala** [vimperator/vimperator-labs#209]
When I use the "quick hint" functionality `f` then most often I have to type a two-digit number, plus enter, because typically the single-digit numbers are all taken up by links in the header.

What if instead of using just numbers, quick hint would number using numbers and letters? i.e.
```
0
...
9
a
...
z
10
11
...
19
1a
...
1z
(etc)
```

That way on most pages following a hint would take just 1 key stroke instead of 2-3.

**Comment by anEffingChamp** [comment]
I initially felt the same when I switched to Vimperator from Vimium. However adjusting to any new system can be tough, so I just got over it. Alphanumerics allowed for faster distinction between entries, because there are more initial characters to choose from. However I find that strictly number input is manually faster, because I can use the number pad at the right of the keyboard. I recommend that you just give yourself some time to adapt to the new system.

**Comment by k0ala** [comment]
@anEffingChamp Thanks for your note. I never used Vimium, in fact Vimperator is my first vim-like plugin.

I just use vim a lot, and since the spirit of vim is to do as much as possible while typing as few keystrokes as possible and moving your hands as little as possible, then I would say that if i have to grab the keypad for the most frequent move (i.e. click on a link) then IMHO the spirit was not conserved.

**Comment by gkatsev** [comment]
You can set which hintcharacters you want to use with `'hintchars'`. See `:h 'hintchars`

**Comment by k0ala** [comment]
@gkatsev very cool :+1:

**Comment by maxauthority** [comment]
Actually the system was designed the way it is (with numbers) so that you
can type part of the link and it will follow the link once it's unique.
This can actually be even faster then the displayed alpha hints, as you can
start writing text immediately after f instead of taking a pause and
mentally thinking about the keys which popup. It takes a bit of getting
used to it though to think about the most unique part of a link.

**Comment by peshoicov** [comment]
I'm using Vimperator for a couple of months and tried Vimuim at home, out of curiosity ... and I can confirm that using letters is **indeed** faster than using the numbers :)

**However**, if you use the approach by @maxauthority - hit "f" and then start typing the text of the link - this is even faster than the letters alone :)

=====

Personal opinion, of course, but decided to share anyway :)
