### ISSUE TITLE
Mozilla to deprecate XPCOM and XUL addons

### ISSUE THREAD

**Issue by gkatsev** [vimperator/vimperator-labs#264]
https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/

They say a 12-18 months time period. But it's unknown how much or whether there will be enough APIs to maintain a plugin like vimperator is right now.

**Comment by miccrun** [comment]
Can we start a prototype using the add-on API, and see how it goes?

**Comment by gkatsev** [comment]
A lot of the power that vimperator has compared to the other plugins (particularly the ones that chrome has) come from a lot of the XPCOM and XUL features. The jetpack/addon api probably has some features available but the new proposed WebExtensions API probably doesn't have enough of the functionality.
I guess right now, the only thing we can do is wait for a bit in addition to speaking out about the APIs that we need to continue having vimperator be as awesome and powerful as it is.

**Comment by The-Compiler** [comment]
From [the Wiki page](https://wiki.mozilla.org/WebExtensions#Additional_APIs):

> Better keyboard shortcut support. We'd like to support Vimperator-type functionality.

**Comment by gkatsev** [comment]
Hopefully there will be enough useful APIs to keep all the features that vimperator has.

**Comment by protrolium** [comment]
This is incredibly disappointing. Vimperator is a tool I use everyday. What kinds of functionality will be lost because of WebExtensions API?

**Comment by gkatsev** [comment]
@protrolium unsure exactly what will be. The most visible thing that will be lost is the vimperator command line.

**Comment by behrmann** [comment]
Currently wishes for the WebExtension API are being collected. I made a request, maybe a few votes on that could help. 

https://webextensions.uservoice.com/forums/315663-webextension-api-ideas/suggestions/9455088-make-sure-add-ons-that-completely-change-the-ui-l

(This is copy of the [pentadactyl issue #82](https://github.com/5digits/dactyl/issues/82))

**Comment by gkatsev** [comment]
I think that https://webextensions.uservoice.com/forums/315663-webextension-api-ideas/suggestions/9439725-ability-to-extend-standard-controls-e-g-location and https://webextensions.uservoice.com/forums/315663-webextension-api-ideas/suggestions/9439896-allow-invoking-external-applications and https://webextensions.uservoice.com/forums/315663-webextension-api-ideas/suggestions/9448173-provide-dom-manipulation-hooks-for-browser-chrome will also be helpful.

**Comment by gkatsev** [comment]
Also, we theoretically have 2 years to go because we could just continue using the last ESR of firefox that was published with the XUL/XPCOM support. :P

**Comment by maxauthority** [comment]
I think, the missing possibilities like not having the old style toolbar
customization support is not that huge. E.g. Vimium on Chrome also has
something like a command line (when pressing o) to show up in the middle of
the screen. Actually this would allow to re-think the visual display of our
command line anyway.

And most other *important* features (apart from some, probably not used at
all like :!cat /my/file) should be possible and actually allow us to get
easily get rid of old, often broken cruft which has accumulated over the
years and focus on the core strengths of Vimperator again: A powerful
browser which makes most common tasks very easy and in a Vim-inspired way.

The REAL problem is, that it'll require a near-complete rewrite, and
lacking resources, we need at least one REALLY motivated hacker who does
the big job of transfering the add-on to the new API.

That said, I also think, the new approach might also have some benefits, as
the new non-XUL approach should have performance advantages (mainly in
terms how Firefox can be optimized), and that's one of the most certain
things Firefox currently needs (clean up old stuff and focus on
performance).

Just my 2 cents,
Martin

**Comment by klaplong** [comment]
Though I'm not very familiar with the Vimperator source (let alone Liberator..) or with Firefox add-on development, but I am very willing to contribute in code or otherwise. Please let me know how I can help!

**Comment by maxauthority** [comment]
Well, I think that's actually perfect, as most code will need to be
rewritten anyway :) So starting to look into the new WebExtensions API and
getting a first skeleton "new" Vimperator with only the very basic feature
(like handling "j" to go down) would be a great start.

Then one could gradually get the old features from the "old" Vimperator
working, either by copying the code (we'll help you show where it is) or
actually quickly rewriting the functionality as many (like accessing
bookmarks or downloads got significantly easier with the WebExtensions over
the XUL approach).

**Comment by gkatsev** [comment]
I'm not going away any time soon :)

also, right now is probably a bit early to try and start up "the new vimperator" because the WebExtensions APIs are currently sorely lacking. Though, learning about the APIs and what's currently available is useful. For example, one limitation (that supposedly will be addressed) is keyboard shortcuts. The chrome API requires you to use a modifier key with your keyboard shortcut right now. Vimium does some crazy stuff (and the similar addon for safari does even crazier stuff) to be able to handle non-modified keyboard shortcuts.
I subscribed to the mozilla extdev mailing list and discourse page to keep up to date with the goings on of the new stuff.

Also, I do agree @maxauthority being able to re-write it from scratch and with limited APIs will allow us to think about it from a new perspective. Though, hopefully, we don't come up with something too crazy :P. Though, at the very least, it'll allow us to make the code nicer and leaner.

P.S., @behrmann's uservoice item is the most voted on item that isn't bullshit :D

**Comment by behrmann** [comment]
On Tue, Aug 25, 2015 at 07:59:11AM -0700, Gary Katsevman wrote:
> P.S., @behrmann's uservoice item is the most voted on item that isn't bullshit :D

Thanks, I'd rather have it be on top to blot out the bullshit. :) I added a note
on the hacky solutions for vim-like bindings in the on Chrome and Safari in the
comments of my uservoice item. A more detailed list of what is needed might be a
helpful thing to add, too. Well, I hope somebody at Mozilla will read that stuff
at some point.

On Tue, Aug 25, 2015 at 07:59:11AM -0700, Gary Katsevman wrote:
> Also, I do agree @maxauthority being able to re-write it from scratch and with limited APIs will allow us to think about it from a new perspective. Though, hopefully, we don't come up with something too crazy :P. Though, at the very least, it'll allow us to make the code nicer and leaner.
>

I rather like my UI as is, but I'm also using Pentadactyl instead of
Vimperator. I would rather see a way to keep the functionality I have (or
rather, the subset of which I use, which includes not interacting with any part
of the Firefox UI but occasionally the preferences page), with code cleanups (on
the Pentadactyl side) being a secondary priority for me.

**Comment by gkatsev** [comment]
Depending on what APIs are added to support will direct how creative we have to get. :P

**Comment by gkatsev** [comment]
Not sure what else to say here.

**Comment by nachoparker** [comment]
Hello, I would like to share my thoughts on this whole wicked situation and publicly ask for cooperation

https://github.com/vimperator/vimperator-labs/issues/705#issuecomment-282019678

**Comment by samrocketman** [comment]
Vimium and other browser equivalents to vimperator are weak and underpowered.  Vimperator is basically the only reason I still use Firefox even though the browser is bloated.
