### ISSUE TITLE
Idea: pushing and pulling multiple tabs to groups

### ISSUE THREAD

**Issue by fenque** [vimperator/vimperator-labs#276]
```
pulltabs[tab][!] {url | index}
                    Pull the tabs from another group.
                    The argument {url | index} is the same as :buffer's argument.

pushtabs[!] {url | index} {groupName} 
stash[!] {url | index} {groupName}
                    Move the current tabs to a group named {groupName}.

                    If the group does not exist, you can use [!] 
                    to automatically create a new group named {groupName} and
                    move the tabs there.
```
Something like this.

**Comment by gkatsev** [comment]
Sounds like a pretty good idea. Probably best to start as a vimperator plugin (commands can be lowercased). Especially since supposedly tabgroups are not going to be shipped by default at some point. At least, that's what they mentioned at some point. Idk whether it's actually happening or not.

**Comment by VdeVatman** [comment]
@gkatsev I was also looking for this feature, it would make my life much easier.

Since I can see it doesn't exist already I was thinking about doing it myself, but this is all I've found about writing vimperator's plugins: liberator://help/developer#writing-plugins.

Could you provide me with the link to vimperator's API or a very easy and tiny plugin to take it as an example and so I could understand how vimperator's plugins work?

**Comment by gkatsev** [comment]
Yeah, unfortunately, the API isn't documented very well. Probably the best I can do right now is show you where there are a bunch of other plugins you can look at. https://github.com/vimpr/vimperator-plugins
