### ISSUE TITLE
color can't display in windows 64bit 42.0b9

### ISSUE THREAD

**Issue by transtone** [vimperator/vimperator-labs#322]
color can't display. It's all gray.

**Comment by timss** [comment]
- es10?
- screenshot?
- vimperatorrc?

Help us help you.

**Comment by Witos** [comment]
Using the same version: colorscheme doesn't change anything, and link tips after pressing 'f' don't appear.

**Comment by Witos** [comment]
vimperatorrc: http://pastebin.com/KHxd1zu8 zenburn from: https://github.com/vimpr/vimperator-colors.git but none of the themes work.

**Comment by timss** [comment]
See #289 and #315. I had to test this myself to indeed confirm this is the same error already reported. Please include a proper screenshot next time, thank you.

As for the bug, it seems to have been fixed in newer builds. After all, you're running a beta build.

I think this should be closed as a duplicate.

**Comment by gkatsev** [comment]
Thanks for looking into it @timss

**Comment by timss** [comment]
Glad to help.
