### ISSUE TITLE
migrate to use jpm

### ISSUE THREAD

**Issue by azatoth** [vimperator/vimperator-labs#356]
Low priority issue, but might be an idea to replace the current (archaic) build system with per mozilla recommended jpm ( https://developer.mozilla.org/en-US/Add-ons/SDK/Tools/jpm).

**Comment by gkatsev** [comment]
This is unlikely to happen because moving to jpm is probably not easy and all the APIs that vimperator uses are being deprecated ( #264 ).
Unless you think that we can use jpm to build the plugin as it currently is? Right now, we basically just put all the files together into a zip file that is called `.xpi`. Plus, there's some file juggling to create the separate vimperator and muttator xpis from using the shared and addon specific code.

**Comment by gkatsev** [comment]
Not sure what else to say here.
