### ISSUE TITLE
Some Vimperator keybindings blocked on GitBook

### ISSUE THREAD

**Issue by aiman** [vimperator/vimperator-labs#373]
For any GitBook, I cannot use `<C-u>`, `<C-d>` or even `<space>` to scroll a page. The problem persists even if I close/collapse the left-hand side table of contents pane. However other keybindings do work, such as `/`.

Here is a link to a chapter on GitBook:
https://97-things-every-x-should-know.gitbooks.io/97-things-every-programmer-should-know/content/en/thing_02/index.html

Does anyone have any advice or suggestions for how to diagnose this issue or work around it?

**Comment by johntyree** [comment]
Looks like they have some javascript that just blanket catches all keypresses?

The real question is "Why is vimperator letting my keypresses through without me telling it to?"

Several other sites have this problem, although someone in the IRC channel seemed to think it was a feature.

**Comment by timss** [comment]
@johntyree Remember that keypresses are handled differently in normal and insert mode (intentionally or not). 

If `<C-i>` is not working in insert mode for a site, for example here on Github by adding underscores (italics), it's not the same as a website eating your keypresses in normal mode. 

Somewhat relevant pull request: https://github.com/vimperator/vimperator-labs/pull/287

That being said, I don't believe this necessarily is the reason for this issue, but rather how `<C-d>` etc. works, versus say `<C-f>`. Trying to look into it now, in short the problem seems to be it doesn't find the correct window and/or its size to be able to scroll.

**Comment by johntyree** [comment]
> If <C-i> is not working in insert mode for a site, for example here on Github by adding underscores (italics), it's not the same as a website eating your keypresses in normal mode.

It is in the sense that key presses that should be captured by vimperator are being let through. I assumed that key press events went through vimperator before the page ever got to see them, is that not correct?

**Comment by timss** [comment]
The matter was discussed a bit on IRC last night, when I asked if anyone remembered the changes done and why. 

>20:58        gkatsev │ I don't think it was really a change it's more like we didn't change anything
>20:59        gkatsev │ so js keybindings end up killing ours since we're not guarding against it

Don't really have much else to bring to the discussion, I'm afraid.

**Comment by gkatsev** [comment]
Fixed by #397.
