### ISSUE TITLE
ContentSeparator lost after hiding statusbar

### ISSUE THREAD

**Issue by SammysHP** [vimperator/vimperator-labs#394]
When the statusbar was hidden, `ContentSeparator` is reset to its default value.

Before:
```
border-top: 1px dotted #444444; display: -moz-box; background: #222222;
```

After:
```
border-top: 1px dotted gray; display: -moz-box;
```

**Comment by demokritos** [comment]
There was my mistake in the variable's name.
By the way, saving the ContentSeparator's value in toggle_off function is not working. I don't know the reason. Since I moved the assignment to the point executed in the initialization, the assignment in toggle_off is not needed.

To toggle the statusline, I use 
```noremap <silent> <F8> :js statusline.setVisibility(statusline.setVisibility.TOGGLE)<CR>```
If I hide and unhide the statusline with F8, ContenSeparator is missing. Deleting the assignment line in toggle_off function fixes this.

**Comment by SammysHP** [comment]
> Since I moved the assignment to the point executed in the initialization

And this initialization happens too early. I tried it without setting it in `toggle_off()` and it didn't work.

But you're right: With my change the value of `ContentSeparator` is lost completely (probably because `highlight.get('ContentSeparator').value` is undefined in `toggle_off()`; `sv.contentSeparator` is set to something empty because I didn't remove the early initialization).

**Comment by demokritos** [comment]
@SammysHP Do you mean that you use your custom highlight style for ```ContentSeparator```? I was not aware of that customization. 
To fix this, we have to figure out why ```ContenSeparator``` is set to a wrong value, correct?

**Comment by SammysHP** [comment]
> Do you mean that you use your custom highlight style for `ContentSeparator`?

Yep.

> To fix this, we have to figure out why `ContenSeparator` is set to a wrong value, correct?

Yes. I assume it has something to do with the scope where `statusline.setVisibility()` is called.
