### ISSUE TITLE
Findbar shows up

### ISSUE THREAD

**Issue by demokritos** [vimperator/vimperator-labs#401]
I am using Firefox beta 45.0b1.
With commit #371, Firefox shows the findbar in typing if the search string is not found.
By the way, one Korean character is composed of multiple inputs. So every time that I search with Korean, the findbar shows up. Furthermore, the input is broken at the moment when the findbar shows up. For example, assume that you find ```안녕```. So, you input ```ㅇ```, ```ㅏ```. Then the findbar shows up because ```아``` is not found in the page. If in this moment, you type fast, the input is broken like ```아ㄴᅟ녕```.
I tried reverting the commit. In this case, the findbar shows up only when I complete the search string and it is not found. To fix this show-up, I commented out ```window.gFindBar._findField.value = str;``` as
```
    find: Services.vc.compare(Services.appinfo.version, "25.0") >= 0 ?
    function (str) {
        let fastFind = this.fastFind;
        this._processUserPattern(str);
        let result = fastFind.find(str, this._linksOnly);
        //window.gFindBar._findField.value = str;
        this._displayFindResult(result, this._backwards);
    } :
```

**Comment by Quicksaver** [comment]
I had forgotten the findbar appears on failed matches. Still even though that happens the command line retains focus, so you should be able to finish your input and it should correct itself at the end. So even if while in the process of typing it says it doesn't find your text, it should find it when you finish typing. Doesn't this happen?

If needed, this is easy to fix with FindBar Tweak installed, it dispatches a ```WillOpenFindBar``` on which it can call ```preventDefault()``` to keep the findbar from opening, and that's that. No such luck with the native Firefox findbar... The only way I see there is to piggyback the findbar's ```open``` method and bailout if the user is typing in Vimperator's command line.

Since I wrote https://github.com/Quicksaver/vimperator-labs/commit/9cce65339a4ab526ac9911a9c0b94a01185b6ee2 I'll be happy to take on this one as a follow-up as well. I just need to know what's the best way to know within the code that the user is typing in the command line, I'm guessing there's there some flag somewhere I can't find. @gkatsev ?

**Comment by demokritos** [comment]
I installed FindBar Tweak and selected 'Always use Quick Findbar'. With this, the problem in typing in Korean disappeared, and I can make the findbar autoclose. In my opinion, vimperator and findbar are not well-matched. Can you stop the findbar appearing? It will also be nice if the problem in Korean input is fixed without the addon. 

With FindBar Tweak installed, searching with "aaaaaaaaaa" gives a message "Pattern not found: aaa".

**Comment by gkatsev** [comment]
I think actually the commit that makes the findbar come up on a failed search is this: https://github.com/vimperator/vimperator-labs/pull/93
@quicksaver any help would be super appreciated. I'll see if I can figure out whether there is some flag or something you can check to know that the user is in the cli.

**Comment by Quicksaver** [comment]
> I think actually the commit that makes the findbar come up on a failed search is this: #93 

Not true anymore, this was overwritten by https://github.com/Quicksaver/vimperator-labs/commit/9cce65339a4ab526ac9911a9c0b94a01185b6ee2. Now it's the [actual findbar showing itself on failed searches](http://mxr.mozilla.org/mozilla-central/source/toolkit/content/widgets/findbar.xml#1165) because Vimperator is using it.

> I installed FindBar Tweak and selected 'Always use Quick Findbar'. With this, the problem in typing in Korean disappeared

This is surprising, I wouldn't think there would be a difference when inputting complex words like in Korean. In this case, preventing the findbar from appearing seems to be the only option, I still wonder what's causing this exactly though...

> With FindBar Tweak installed, searching with "aaaaaaaaaa" gives a message "Pattern not found: aaa".

This is expected. If it can't find "aaa" then it definitely won't find "aaaaaaaaaa", so it doesn't even try to look.

**Comment by SammysHP** [comment]
>> With FindBar Tweak installed, searching with "aaaaaaaaaa" gives a message "Pattern not found: aaa".
> 
> This is expected. If it can't find "aaa" then it definitely won't find "aaaaaaaaaa", so it doesn't even try to look.

This is really confusing. It is much more intuitive to show the complete search string.

**Comment by SammysHP** [comment]
btw: The aaaaaaa thing is not completely fixed. Now it shows
```
Pattern not found: a
```
and afterwards
```
Pattern not found: aaaaaaa
```

Both is logged in `:messages`.
