### ISSUE TITLE
Vimperator "forgets" last search pattern between tabs

### ISSUE THREAD

**Issue by axbender** [vimperator/vimperator-labs#426]
After (successfully) searching a pattern in one page = tab, using "n" or "N" in the next/another tab will not find that pattern. This used to work in 43.

**Comment by gkatsev** [comment]
So it does. Not sure how this happened. @Quicksaver would you know?

**Comment by Quicksaver** [comment]
That's because of the per-tab nature of the findbar. Before, Vimperator was running searches itself so it was storing the search query, but now it's just a proxy for the findbar. When switching to a new tab, its findbar will be empty so it can't find anything.

We have two choices:
- adopt per-tab behavior as well and try to use a query from another tab (the last search run basically) when the current tab has none. But if you run a search in tab A for "a", then switch to tab B and search for "b", then switch back to tab A and press "n" it will still find "a" because that's what you searched for there.
- global behavior, "n" will already find the last word you searched for globally regardless of in what tab that happened. So in the example above, pressing "n" in tab A at the end will search for "b".

I'm not really a Vimperator user, so I'm not sure which behavior would be expected/optimal.

(This is also something that causes some confusion in the findbar itself, which FindBar Tweak tries to address as well, but I don't think any of its behavioral fixes can be applied here TBH.)

**Comment by gkatsev** [comment]
Ah, good to know. Didn't know that firefox's search was per-tab.
The global behavior is probably what is expected for vimperator rather than the per-tab behavior.

**Comment by Quicksaver** [comment]
Then I'll try to whip up a quick patch later today when I fix #428. :)

**Comment by gkatsev** [comment]
That would be amazing. I appreciate your help so much, @Quicksaver!

**Comment by Quicksaver** [comment]
Don't mention it. Since I was the one who originally rewrote the whole finder module in the first place, the least I can do is cleanup my own mess. :)

**Comment by axbender** [comment]
Thanks that you take a look into that. Personally, I'd prefer the global "option", as this is my favorite use case. I often have many tabs open displaying pages found by using a search engine, and want to search for a specific word. Using "n" or "N" is/was ;-) very helpful here.
Also, I'd find it very useful not to have to search for the same pattern again only in order to get search highlighting (which was a problem even before FF43), i.e. searching in tab one gives me all the matches highlighted; then switching to tab two would require me to re-enter the exact same search pattern just to have all the matches highlighted where pressing "n" or "N" (like in gvim) should suffice...

**Comment by SammysHP** [comment]
Sadly this is not fixed. When you switch the tab, press `n` and the search term is not found, no warning is shown.

**Comment by gkatsev** [comment]
@SammysHP as in it doesn't show a warning that the item isn't found?

**Comment by timss** [comment]
Odd. Using ff6151e (3.12.0) it is working for me, both successful searches and `Pattern not found: <term>`. FF 44.0.2.

**Comment by SammysHP** [comment]
@gkatsev yes.

@timss I'll try it again.

**Comment by SammysHP** [comment]
Tested it again.

1. Open two tabs.
1. On one tab do <kbd>/</kbd>`asdfasdfasd`<kbd>CR</kbd> which results in a red warning "Pattern not found: …".
1. Press <kbd>Esc</kbd>.
1. Switch to the second tab and press <kbd>n</kbd>. Nothing happens.

Do the same with a search term that is present at both tabs, then the search works as expected.

**Comment by Quicksaver** [comment]
Hopefully fixed it for good this time in #443.

**Comment by SammysHP** [comment]
Thanks, much better now!

**Comment by timss** [comment]
Nice, good job @Quicksaver! 

Thanks for reporting this again @SammysHP.
