### ISSUE TITLE
Tabs in linuxquestions.com member profile do not highlight

### ISSUE THREAD

**Issue by Rodartist** [vimperator/vimperator-labs#461]
##### Issue type:

- Bug report

##### Version:

```
Version Information
Vimperator:	3.12.0 (created: 2016/02/28 22:07:56)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:
linuxquestion.org ~ a members profile any member tabs do not highlight

no highlight
##### Expected behavior:
highlights when pressing f key

highlighted tabs
##### Steps to reproduce:
Click on view public profile of a forum member and try to highlight.

**Comment by timss** [comment]
Updated as per template.

Please supply a URL to test with.

**Comment by Rodartist** [comment]
Here is my public profile:

http://www.linuxquestions.org/questions/user/slackartist-1020633/

**Comment by timss** [comment]
I created an account and tested. Each tab is just a `<li>` element in an `<ul>` with a javascript event that triggers when clicked. Not possible to highlight using Vimperator, because there is no way to tell if the element is a "link", sorry. 

![tabs](http://i.imgur.com/KMqS0Sd.png)

![code](http://i.imgur.com/QBKozN9.png)

Blame website developers who ignore standards and don't use anchors where appropriate.
