### ISSUE TITLE
3.13.1 not work with FF 47, how to install 3.14 now?

### ISSUE THREAD

**Issue by bigeast** [vimperator/vimperator-labs#532]
##### Issue type:

- Version compatibility

##### Version:

```
Vimperator: 3.13.1 (created: 2016/05/04 01:34:00)
Firefox: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
```

##### Description:

ReferenceError: Application is not defined

##### Expected behavior:

I went to the official website of Vimperator, and found a newer version 3.14 has already been there, which is said to be compatiable with FF 47. But it can't be installed because it's not been signed!

I guess version 3.14 will be available soon from mozilla site, but how to install it now? I just can't wait...

**Comment by yupyupp** [comment]
While I cannot comment on how long it will take for the update to make it to addons.mozillia.org you can install the .xpi from the github release page by setting "xpinstall.signatures.required" to false in about:config. Since the download from github hasn't been signed by Mozilla, firefox will give you a warning about installing an unsigned addon but it will still allow you to do so.

**Comment by gkatsev** [comment]
3.14.0 is now fully reviewed and should be available.
