### ISSUE TITLE
Vimperator forces ''open new window in new tabs" option

### ISSUE THREAD

**Issue by BenoitAverty** [vimperator/vimperator-labs#598]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.14.0 (created: 2016/06/07 23:58:16)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

I don't use tabs in firefox. To achieve that, among other things, I unchecked the option in firefox called "open new windows in a new tab instead". However, since installing vimperator, I noticed that links with "target=_blank" open in new tabs. I checked in the preference and the option is checked. When I uncheck it then come back in the preferences, it's checked again. I'm almost certain vimperator is doing that because this setting was working perfectly before I installed vimperator.

##### Expected behavior:
The "open new windows in a new tab instead" option stays unchecked and links with target="_blank" open in a new window.

##### Steps to reproduce:

Install firefox and vimperator, uncheck this option and open a target="_blank" link (for example any link in a email in gmail). The link will open in a new tab. Go back to settings : the option will be checked again.

Thanks in advance.

**Comment by jayeshbadwaik** [comment]
I confirm this bug, and I would like this to be fixed too.

**Comment by SammysHP** [comment]
See https://github.com/vimperator/vimperator-labs/blob/8f0025eef320846d210ee97b02a38973f7cbb13a/common/content/tabs.js#L1138-L1162

**Comment by BenoitAverty** [comment]
Thanks! That was it !

**Comment by joefiesta** [comment]
I too have this problem.  I am running Vimperator 3.15.0 and the problem occurs there as well.  While I can see that the above pointed out in the code where the problem lies, does that mean it will be fixed?    I am only a casual user of Vimperator, so I don't know how to modify it's source or change it's behavior by adding code somewhere.

**Comment by SammysHP** [comment]
You can use `:set popup` to change that behavior. I'm not sure if it works correctly, though. There are just three states (`3,0`, `2,0` and `1,2`), but both preferences can interact in more ways AFAICS:

http://kb.mozillazine.org/Browser.link.open_newwindow
http://kb.mozillazine.org/Browser.link.open_newwindow.restriction

**Comment by joefiesta** [comment]
I found a very old thread about this exact problem.   (It gets very long, and at the end branches off to a long discussion about messaging.)  http://www.mozdev.org/pipermail/vimperator/2009-September/004763.html

Here somesays says "fixed" about the problem, but it doesn't seem it was fixed.  Or it just broke again.

As to your suggestions, SammysHP, I don't know exactly how I am supposed to use the information you gave.  I have my own RC file, but I only use Vimperator for one thing:  the follow command.  I tried "set browser.link.open_newwindow=2" in my RC file, but that produces an error.

**Comment by SammysHP** [comment]
`:help 'popup'`

**Comment by joefiesta** [comment]
Thanks SammysHp.  I put "set popups=window" in my RC and Firefox is happy and unchecks "Open new windows in a new tab instead"  This is great, but doesn't thrill me.  Now, if I change the option in Firefox, it gets changed back by Vimperator.  Oh well, I guess.  But, this must be new behavior, but not sure it's Vim because I've been on 3.15 for a long time.  Anyway, another question, if I might:

I found this in the SET help:      
            

:set!:set-!:se[t]! {preference}={value}
        
            Change any Firefox {preference} (those in the about:config
            window). You can also reset/delete those preferences with
            :set! preference&

I tried using :set! and it seems not to work.   I put
     :set! browser.link.open_newwindow=1 
in my Vim RC and, while not being flagged as an error, it doesn't set the item to 1.  
Can you explain why?  (Yes, I know.. why questions aren't easy.)

**Comment by joefiesta** [comment]
And, I tried this, also, to no avail:

 :set! browser.cache.disk.capacity=359400      

It LOOKS LIKE the word ANY (in "Change any Firefox {preference} ...") is not correct.  Or, I'm missing something.
