### ISSUE TITLE
Wrong behaviour with TiddlyWiki - Ctrl-P invoked print dialogue instead of moving to previous tab

### ISSUE THREAD

**Issue by JDurston** [vimperator/vimperator-labs#629]
##### Issue type:

- Bug report
##### Version:

```
Vimperator: 3.15.0 (created: 2016/10/05 01:11:26)
Firefox:    Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0
```
##### Description:

I use [TiddlyWiki](http://tiddlywiki.com/) with Firefox. 
I noticed, that when switching tabs (with <kbd>Ctrl-n</kbd> / <kbd>Ctrl-p</kbd>), if I switched to a tab containing a TiddlyWiki, pressing <kbd>Ctrl-p</kbd> would invoke the Firefox **print** dialogue! Annoying because it abruptly stopped my run of scrolling back through multiple tabs.

Further investigation revealed that this only seems to happen when a TiddlyWiki page is _being loaded_.

For ease of replication: it happens on the TiddlyWiki website too (since it seems to be some instance of a TiddlyWiki).

**NOTE:** Issue is also present with:
`$ firefox -no-remote -P`
and
`$ firefox -no-remote -P <fresh profile> -vimperator "+u NONE"`
##### Expected behavior:
1. With a TiddlyWiki, OR on the TiddlyWiki website
2. Press <kbd>r</kbd>, and then quickly (before the page is finished loading)...
3. ...press <kbd>Ctrl-p</kbd>
4. One would _expect_ Vimperator to cause Firefox to switch to the previous tab
##### Steps to reproduce:
1. Go to [the TiddlyWiki website](http://tiddlywiki.com/)
2. Press <kbd>r</kbd>, and then quickly (before the page is finished loading)...
3. ...press <kbd>Ctrl-p</kbd>
4. Vimperator _should_ cause Firefox to switch to the previous tab, but instead the _print dialogue is invoked_

**Comment by timss** [comment]
Thanks for submitting this issue and sorry for the late reply, @JDurston.

Gave the TiddlyWiki website a try and it doesn't seem to be specific to TiddlyWiki, but rather that some of its content is getting focused right as you reload the website. 

If you have the `focuscontent` option enabled, you'll see that by refreshing the website (`r`) it goes into insert mode for a brief second, at which point `C-p` is no longer bound to "previous tab". You can reproduce this on any website, such as clicking the comment box on this issue and pressing `C-p`.

If this is the root cause of your issue, you could try to escape insert mode before pressing `C-p`, or remap insert mode `C-p`:

    inoremap <C-p> <ESC><C-p>

Please re-open if I'm way off this didn't help you resolve this issue.
