### ISSUE TITLE
How to find the first match?

### ISSUE THREAD

**Issue by roxma** [vimperator/vimperator-labs#631]
I type `/abc` to find "abc" in the page. When I want the first match,  `gg/abc` doesn't work for me.

**Comment by timss** [comment]
Unlike Vim, `gg` or other motions does not reset which match is next selected with `n` or `N`. This is likely because it would be very difficult and expensive to keep track of what is visible on the screen, when stuff is moved, and would be increasingly challenging with dynamic content.

As of now, your best bet is to repeat the search, i.e. do a `:noh` and search again.

**Comment by nschley** [comment]
@roxma, @timss  ~
The root of the behavior lies with the usually invisible cursor.
The cursor follows the search match.  When the user wants to get the 1st match on a page after having done a search on the page already, s/he must first get the cursor to the top of the page.  At that point `n` will do the needful.
Perhaps there's a config option that affects this behavior, but I find that `:noh` does _not_ do the trick; it does not change the cursor position.
What works for me:
> 
> **`cggn`**
>
or, for the last match on a page:
> 
> **`cGN`**
>
Notes
1.  Highlight selection is different from cursor selection, so if you want to copy the match at the cursor, you need to hit `v` and select it before copying.
2.  In visual mode, use `^C` instead of `y` & `Y` to copy (yank) the cursor selection.

**Comment by liviu-** [comment]
Neither of the above solutions works for me in pdf.js using Vimperator 3.16.0, Firefox 54, Linux. I end up having to refresh the page to reset the cursor i.e. `rggn`
