### ISSUE TITLE
Suggestion: enable SSL icon by default

### ISSUE THREAD

**Issue by rrooij** [vimperator/vimperator-labs#644]
##### Issue type:

- Feature request

##### Version:

```
Vimperator:	3.15.0 (created: 2016/10/05 01:11:26)
Firefox:	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
```

##### Description:

The SSL icon is not enabled by default. When the `gui` setting is set to `none`, people can fail to see whether the site has a trusted certificate or not. This can cause people to visit bad sites by accident which can cause harm to the user.

##### Expected behavior:

The ssl-icon enabled by default in the statusline. I would suggest to put it left to the address location.

##### Steps to reproduce:

1. Default vimperattorrc
2. `set gui=none`
3. No way to see if site is secure by default

**Comment by timss** [comment]
Agree, and this is something I always include in my personal configuration:

    status=input,location,bookmark,tabcount,ssl

I'd say it's better if the icon is put to the right of the location (address) though, since then it won't be skewed to the left depending on the length of the url of current page. If it's before/after bookmark and tabcount I have no big opinion about.

Would you be interested in sending in a pull request with the change? 

- https://github.com/vimperator/vimperator-labs/blob/71e029e4ef323448ff04d21ea49e5b19f90bbbf0/common/content/statusline.js#L423
- https://github.com/vimperator/vimperator-labs/blob/b9c1f0db0ec45fb09a24254629813b272d7e210f/common/locale/ja/options.xml
- https://github.com/vimperator/vimperator-labs/blob/3decabe4e0d37122f332cd626a20e4055025d742/common/locale/en-US/options.xml

**Comment by rrooij** [comment]
@timss
The SSL icon to the right of the location is indeed better so it doesn't get skewed.

I'm interested in doing a pull request. It's a fun way of getting to know the codebase of Vimperator better. Thanks!
