### ISSUE TITLE
make xpi doesn't work(vimperator & muttator)

### ISSUE THREAD

**Issue by drselump14** [vimperator/vimperator-labs#648]
##### Issue type:
- Bug report

##### Version:

```
latest master branch
```

##### Description:
make xpi produce errors like below

Building XPI...
Including en-US documentation
Including ja documentation
Replacing UUID, VERSION, DATE and UPDATEURL tags
sed: 1: "../downloads/muttator-1 ...": invalid command code .
sed: 1: "../downloads/muttator-1 ...": invalid command code .
sed: 1: "../downloads/muttator-u ...": invalid command code .
make: *** [xpi] Error 1

##### Expected behavior:
make produce xpi file

##### Steps to reproduce:

make xpi

**Comment by stvnw** [comment]
Some versions of `sed` (OS X, BSD?) require an argument to `-i`, otherwise the following token is interpreted as the filename extension and subsequent tokens are misinterpreted. This issue is crudely fixed by adding the '-e' flag for consistency with other calls to `sed` in the Makefile, though it should be noted that said calls only work by and `-e` is being misinterpreted as the argument to `-i`.

This was introduced in https://github.com/vimperator/vimperator-labs/commit/b3bd8072309815e15e0c56d76890b5564fd5e69c

**Comment by drselump14** [comment]
thanks @stvnw ... you're right, I'm using OSX ... I hope your fix patch will be merged ASAP
