### ISSUE TITLE
keys not work!

### ISSUE THREAD

**Issue by dehivix** [vimperator/vimperator-labs#685]
##### Issue type:

- Version compatibility

##### Version:

```
vimperator 3.15.0
FF 51.0.1
```

##### Description:
keys like t or T for open new tab navigation not work only show commands and not autocomplete from FF history, and the keys d for close, f for follow, y for copy, gt or Gt not work since this new update

**Comment by timss** [comment]
Thanks for reporting this issue, but this seems to be a duplicate of #568 and was fixed in #675, ultimately released as [Vimperator 3.16](https://github.com/vimperator/vimperator-labs/releases/tag/vimperator-3.16.0). New version coming on [AMO](https://addons.mozilla.org/en-US/firefox/addon/vimperator/) soon™.

**Comment by dehivix** [comment]
oh great! thanks.
