### ISSUE TITLE
Unable to install custom signed version

### ISSUE THREAD

**Issue by brennovich** [vimperator/vimperator-labs#693]
##### Issue type:

- Version compatibility

##### Version:

```
Custom signed version
```

##### Description:

In order to get early access to vimperator `3.16` which fixes issues with Firefox `51` I'm trying to build a custom signed extension.

##### Expected behavior:

I'd expect a successful instalation. But I'm getting a error when installing telling that the extension isn't compatible with firefox `51`

##### Steps to reproduce:

1. Build asigned version of the extension `make sign`
2. install it through `Install add-on from File` option

**Comment by ma8ma** [comment]
@brennovich Need review by AMO. You submit signed add-on using [the form](https://addons.mozilla.org/en-US/developers/addon/submit/distribution) (for self-distribution, automatically review). See [MDN page](https://developer.mozilla.org/en-US/Add-ons/Distribution#Submitting_to_AMO).

P.S. I'm going to append about submitting add-on to README 👍

**Comment by brennovich** [comment]
@ma8ma It was already uploaded when I executed `make sign`, but I cleaned up uploaded versions and tried via form and it worked \o/

Thanks for the instructions ;)

--

I did read some issues and notice the community and current maintainers talking about the lack of developers. Well, I think I'm able to help! I have no experience in developing Firefox extensions but I have some experience with Javascript. Can you indicate some issue to me start on contributing?

**Comment by gkatsev** [comment]
@brennovich any help would be awesome! One simple thing to do is perhaps run nightly builds and fixing any issues. Or perhaps take a look at one of the open issues and try fixing it.
Another option is looking at https://github.com/vimperator/vimperator-labs/issues/688 and https://github.com/vimperator/vimperator-labs/issues/687 and figuring out how to address those items as well.

Also, if you're on IRC, we can try and help out on a more real-time basis, but otherwise, just open issues and PRs!
