### ISSUE TITLE
:tabopen opens child tabs with Tree Style Tab

### ISSUE THREAD

**Issue by cizmazia** [vimperator/vimperator-labs#740]
##### Issue type:

- Bug report

##### Version:

```
Vimperator:	3.16.0 (created: 2017/02/01 00:55:15)
Firefox:	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

Tree Style Tab 0.19.2017031101
```

##### Description:

`:tabopen` opens a child tab instead of a standalone tab with Tree Style Tab.

##### Expected behavior:

`:tabopen` should open a standalone tab like `Ctrl`+`T`. It worked this way with the previous versions of Firefox/Vimperator.

##### Workaround:

`nmap t <C-t>:open<Space>`

##### Steps to reproduce:

Install the [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) add-on and compare the behavior of `:tabopen` and `Ctrl`+`T`.

**Comment by richardb64** [comment]
Confirmed.

The same problem affects the `P` normal mode key binding ("paste new buffer").  That always used to open a new independent tab, but now it opens a child of whatever tab happens to be current.

I suspect this is a TST problem, though perhaps a workaround in Vimperator is possible.  The difference in behaviour between `Ctrl+T` and anything that Vimperator does is due to commit piroor/treestyletab@6d0199b, which makes TST try a lot harder to create tabs as children if the new tab has an "owner".  At least, reverting that commit restores the normal behaviour for both `:tabopen` and `P`.

**Comment by richardb64** [comment]
Looking into the history of this issue, it's gone on for about a year... and there may be two conflicting requirements.  A strict understanding of the Firefox API suggests that the current TST behaviour is actually correct (which is why the recent change was made - somebody complained that TST sometimes wasn't making child tabs when it _should_ be).  But that breaks Vimperator's behaviour.

A new issue has been opened in TST (piroor/treestyletab#1264) about this.  But reading @piroor's comment [here](https://github.com/5digits/dactyl/issues/140#issuecomment-184127678), maybe the best answer is for Vimperator to use a different API and avoid the problem altogether, eg. instead of `browser.loadOneTab()` it could do `browser.addTab("",{relatedToCurrent:false})`.  (Disclaimer: I'm no FF API expert, so I've no idea whether it really is as simple as that!)

**Comment by benp3** [comment]
I found the workaround posted above didn't quite work for me, but this variation did
`nmap t <C-t><Esc><Esc>:open<Space>`

**Comment by zzbennett** [comment]
`nmap t <M-t><esc>:open<Space>` for mac users

**Comment by axujen** [comment]
Another workaround i found
```set activate-=tabopen```
or
```map t :tabopen! ```
Basically this has something to do with the activate setting which activates tabs after opening "i still not sure what that means", so disabling it somehow fixes the issue.
you can also you ```set activate=``` to disable it altogether

**Comment by deiwin** [comment]
Any chance of getting a new version with the fix for this?
