### ISSUE TITLE
Scrolling tab bar with "Remember password?" dialog active makes dialog move outside of window.

### ISSUE THREAD

**Issue by R030t1** [vimperator/vimperator-labs#784]
##### Issue type:

- Bug report

##### Version:

```
Version Information
Vimperator: 3.16.1 (created: 2017/02/01 00:55:15)
Firefox: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
```

##### Description:

Removing UI elements as in the case of `gui=none,tabs` makes Firefox rely on code which leaves the UI in a strange state. A dialog will sometimes be drawn outside the border of the window, pointing to where the tab would be if the window were extended.

##### Expected behavior:

That the dialog be clamped to the extents of the Window, or other contextually appropriate action be taken.

##### Steps to reproduce:

Open many tabs and make the window smaller than the available desktop space. Execute `set gui=none,tabs` and then log in to a website that does not yet have password storage preferences set. When the dialog pops up, scroll the mouse on the tab bar so that the logged in webpage's tab is hidden.

##### Comments:

See https://bugzilla.mozilla.org/show_bug.cgi?id=1355000 and https://bugzilla.mozilla.org/show_bug.cgi?id=1376274. I think this is more appropriate for the Mozilla tracker, but they may not fix it.

**Comment by SammysHP** [comment]
These dialogs use some ugly code. It is not intended to remove parts of the GUI and there is not much we can do. Another great example is the "permission request" popup that is anchored at the left side of the navigation bar and is flickering when the navigation bar is hidden.

I'd suggest "won't fix" as there's probably not much we can do and because these issues are obsolete once Vimperator doesn't work at all anymore.

**Comment by R030t1** [comment]
By that logic, why maintain any software at all?

Did you read the reports on the Mozilla tracker? One of the developers states (as far as I understood it) that the current behavior exists because the code already tries to handle the situation that Vimperator creates. If it didn't, the dialog would likely not appear at all.

**Comment by SammysHP** [comment]
I'm still of the opinion that this can only be fixed by Firefox and we are not Firefox developers here. There are some upstream bug reports which you already linked.

Regarding maintenance: Vimperator is not really maintained anymore for years. Now it is even worse because it will be useless with newer versions of Firefox starting in November. We still accept pull requests and try to fix major problems if we can.

**Comment by R030t1** [comment]
Fair enough, I didn't really expect anyone to do much with this.

What changes are in the Firefox versions starting in November?

**Comment by SammysHP** [comment]
New addon architecture which requires a complete rewrite of the addon.

**Comment by R030t1** [comment]
I assume there's no provisions for backwards compatibility? Do you have a link to the proposal?

**Comment by Koushien** [comment]
Reading #705 should fill you in.
