### ISSUE TITLE
Support for basilisk browser

### ISSUE THREAD

**Issue by vp1981** [vimperator/vimperator-labs#814]
##### Issue type:

- Feature request

##### Description:

As Firefox 57 allows only WebExt extensions vimperator has no direct way to be run on Firefox 57+. But recently palemoon project released they experimental browser Basilisk (https://www.basilisk-browser.org/). I tried it on Windows with sereval my favorite extensions:
- Ublock Origin (1.14.18)
- NoScript (5.1.7)
- Vimperator (3.16.0)
- Flashgot (1.5.6.14)

All they seem to work fine, except that I can't open options for vimperator.

May be it is worth to maintain vimperator to provide support for Basilisk?

**Comment by michal-h21** [comment]
I installed Basilisk on Fedora and basic things seems to work, except for stuff that needs to access the system - so configurations in `.vimperatorrc` don't have any effect, help doesn't work and external command execution doesn't work as well.

**Comment by SammysHP** [comment]
This is an extension for Firefox. We never actively supported other browsers. Feel free to start a fork of Vimperator.

**Comment by galenhuntington** [comment]
The problem is that Vimperator relies on `platformVersion` to decide what code to run in `io.js`, but on Basilisk it returns the Goanna version instead of the Firefox equivalent, and so invalid code is run that causes that module to fail.  See MoonchildProductions/moebius#198.

You can fix it yourself by replacing this line

https://github.com/vimperator/vimperator-labs/blob/master/common/content/io.js#L10

with a hardcoded version, say `const VERSION = "55.0";`.  It's not pretty, but it fixed the above problems for me.
